version: '3'
services:
  app:
    build:
      context: .
    env_file:
      - ./environments/db.env
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/tumiki
      - public-data:/tumiki/public
      - tmp-data:/tumiki/tmp
      - log-data:/tumiki/log
    depends_on:
      - db
    container_name: TUMIKI_app
  db:
    image: mysql:5.7
    env_file:
      - ./environments/db.env
    volumes:
      - db-data:/var/lib/mysql
    container_name: TUMIKI_db
  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/tumiki/public
      - tmp-data:/tumiki/tmp
    ports:
      - 8080:80
    depends_on:
      - app
    container_name: TUMIKI_web
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:
